### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by LiXiangDeng** [rhtm02/PU-Transformer#1]
你好，请问这个代码应该如何运行起来呢，
from knn_cuda import KNN

from pointnet_utils import pointnet2_utils
一些库好像并没有找到 请问是否是忘记提交了 以及方便更新您的实验环境，十分感谢

**Comment by rhtm02** [comment]
from knn_cuda import KNN is installed from https://github.com/unlimblue/KNN_CUDA
from pointnet_utils import pointnet2_utils is installed from https://github.com/erikwijmans/Pointnet2_PyTorch

maybe above libraries not used in my code.
