### ISSUE TITLE
LOSS 

### ISSUE THREAD

**Issue by LiXiangDeng** [rhtm02/PU-Transformer#2]
您好 我运行了您的代码 但是在阅读您的代码后 发现您的CD HD P2F的指标结果好像还没有更新到代码里 不知道您是否方便提供  尤其是P2F的指标 应该如何实现  十分抱歉再次打扰您

**Comment by rhtm02** [comment]
p2f is using "evaluation code" folder at https://github.com/guochengqian/PU-GCN repository. 
CD is loss in loss folder, HD is max value of result of CD.

**Comment by Chantec** [comment]
> 


> p2f is using "evaluation code" folder at https://github.com/guochengqian/PU-GCN repository. CD is loss in loss folder, HD is max value of result of CD.



> 您好 我运行了您的代码 但是在阅读您的代码后 发现您的CD HD P2F的指标结果好像还没有更新到代码里 不知道您是否方便提供 尤其是P2F的指标 应该如何实现 十分抱歉再次打扰您



> 您好 我运行了您的代码 但是在阅读您的代码后 发现您的CD HD P2F的指标结果好像还没有更新到代码里 不知道您是否方便提供 尤其是P2F的指标 应该如何实现 十分抱歉再次打扰您

请问您后面实现p2f了吗
