### ISSUE TITLE
about evaluation

### ISSUE THREAD

**Issue by Chantec** [rhtm02/PU-Transformer#4]
Thanks for your code.Could you please provide the evaluation code？

**Comment by rhtm02** [comment]
i used evaluation code for p2f in [link](https://github.com/guochengqian/PU-GCN/tree/master/evaluation_code)

**Comment by Chantec** [comment]
> i used evaluation code for p2f in [link](https://github.com/guochengqian/PU-GCN/tree/master/evaluation_code)

thanks!

**Comment by rhtm02** [comment]
Yes train.py is final code
